import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, timer } from 'rxjs';
import { map, tap } from 'rxjs/operators';

export interface User {
  firstName: string;
  lastName: string;
  email: string;
}

const filter = (query: string) => ({ email, firstName, lastName }: User): boolean =>
  `${email}${firstName}${lastName}`.toLowerCase().includes(query);

@Injectable({
  providedIn: 'root'
})
export class DataService {
  dataFromHttp = this.http.get<any[]>(`https://jsonplaceholder.typicode.com/users`).pipe(
    tap(console.log),
  );

  constructor(private http: HttpClient) { }
  search(query: string, amount: number): Observable<User[]> {
    return timer(Math.random() * 1000 + 1000).pipe(
      map(() => VALUES.filter(filter(query.toLowerCase()))),
      map(res => res.slice(0, amount)),
    );
  }
}

const VALUES: User[] = [
  {
    firstName: 'Levon',
    lastName: 'Deelay',
    email: 'ldeelay0@spotify.com'
  }, {
    firstName: 'Therese',
    lastName: 'Felstead',
    email: 'tfelstead1@ustream.tv'
  }, {
    firstName: 'Brena',
    lastName: 'Siderfin',
    email: 'bsiderfin2@indiegogo.com'
  }, {
    firstName: 'Quintilla',
    lastName: 'McKennan',
    email: 'qmckennan3@hatena.ne.jp'
  }, {
    firstName: 'Raynell',
    lastName: 'Stansell',
    email: 'rstansell4@mit.edu'
  }, {
    firstName: 'Emmie',
    lastName: 'Noyes',
    email: 'enoyes5@freewebs.com'
  }, {
    firstName: 'Hyman',
    lastName: 'Imlin',
    email: 'himlin6@wix.com'
  }, {
    firstName: 'Raul',
    lastName: 'Sygroves',
    email: 'rsygroves7@springer.com'
  }, {
    firstName: 'Kaitlynn',
    lastName: 'Amiranda',
    email: 'kamiranda8@archive.org'
  }, {
    firstName: 'Jude',
    lastName: 'Shawe',
    email: 'jshawe9@hexun.com'
  }, {
    firstName: 'Cosmo',
    lastName: 'Pleavin',
    email: 'cpleavina@reference.com'
  }, {
    firstName: 'Giulia',
    lastName: 'Flarity',
    email: 'gflarityb@clickbank.net'
  }, {
    firstName: 'Tarah',
    lastName: 'Karolyi',
    email: 'tkarolyic@google.cn'
  }, {
    firstName: 'Marjory',
    lastName: 'Millwater',
    email: 'mmillwaterd@statcounter.com'
  }, {
    firstName: 'Edwin',
    lastName: 'Pietz',
    email: 'epietze@archive.org'
  }, {
    firstName: 'Hendrika',
    lastName: 'Shallow',
    email: 'hshallowf@guardian.co.uk'
  }, {
    firstName: 'Ceil',
    lastName: 'Stilwell',
    email: 'cstilwellg@creativecommons.org'
  }, {
    firstName: 'Ellie',
    lastName: 'Hurley',
    email: 'ehurleyh@sfgate.com'
  }, {
    firstName: 'Ingaborg',
    lastName: 'Tatam',
    email: 'itatami@theguardian.com'
  }, {
    firstName: 'Dyna',
    lastName: 'Velti',
    email: 'dveltij@uol.com.br'
  }, {
    firstName: 'Charmaine',
    lastName: 'Beckley',
    email: 'cbeckleyk@utexas.edu'
  }, {
    firstName: 'Ketty',
    lastName: 'Voller',
    email: 'kvollerl@opera.com'
  }, {
    firstName: 'Rayshell',
    lastName: 'Casaccio',
    email: 'rcasacciom@over-blog.com'
  }, {
    firstName: 'Leupold',
    lastName: 'Anslow',
    email: 'lanslown@typepad.com'
  }, {
    firstName: 'Susanne',
    lastName: 'McVane',
    email: 'smcvaneo@sourceforge.net'
  }, {
    firstName: 'Tova',
    lastName: 'Swynfen',
    email: 'tswynfenp@facebook.com'
  }, {
    firstName: 'Allys',
    lastName: 'Van der Spohr',
    email: 'avanderspohrq@domainmarket.com'
  }, {
    firstName: 'Sheilah',
    lastName: 'Josiah',
    email: 'sjosiahr@1und1.de'
  }, {
    firstName: 'Christoper',
    lastName: 'Francesco',
    email: 'cfrancescos@cafepress.com'
  }, {
    firstName: 'Velma',
    lastName: 'Pietesch',
    email: 'vpietescht@skyrock.com'
  }, {
    firstName: 'Bertram',
    lastName: 'Patey',
    email: 'bpateyu@cafepress.com'
  }, {
    firstName: 'Ivar',
    lastName: 'Olivas',
    email: 'iolivasv@arizona.edu'
  }, {
    firstName: 'Eadmund',
    lastName: 'Bruin',
    email: 'ebruinw@infoseek.co.jp'
  }, {
    firstName: 'Brig',
    lastName: 'Legon',
    email: 'blegonx@arstechnica.com'
  }, {
    firstName: 'Skye',
    lastName: 'Oldam',
    email: 'soldamy@blinklist.com'
  }, {
    firstName: 'Nate',
    lastName: 'Filon',
    email: 'nfilonz@cbsnews.com'
  }, {
    firstName: 'Irina',
    lastName: 'Thompkins',
    email: 'ithompkins10@google.com'
  }, {
    firstName: 'Calvin',
    lastName: 'Ethelstone',
    email: 'cethelstone11@psu.edu'
  }, {
    firstName: 'Pall',
    lastName: 'Banisch',
    email: 'pbanisch12@multiply.com'
  }, {
    firstName: 'Rouvin',
    lastName: 'Gooble',
    email: 'rgooble13@time.com'
  }, {
    firstName: 'Tyrone',
    lastName: 'Biles',
    email: 'tbiles14@hp.com'
  }, {
    firstName: 'Dorine',
    lastName: 'Bockett',
    email: 'dbockett15@mozilla.com'
  }, {
    firstName: 'Kienan',
    lastName: 'Eakle',
    email: 'keakle16@ezinearticles.com'
  }, {
    firstName: 'Sheff',
    lastName: 'Skene',
    email: 'sskene17@facebook.com'
  }, {
    firstName: 'Caroline',
    lastName: 'Death',
    email: 'cdeath18@ezinearticles.com'
  }, {
    firstName: 'Marcia',
    lastName: 'Liversage',
    email: 'mliversage19@ihg.com'
  }, {
    firstName: 'Evey',
    lastName: 'Purkess',
    email: 'epurkess1a@sourceforge.net'
  }, {
    firstName: 'Sal',
    lastName: 'Willcot',
    email: 'swillcot1b@blogger.com'
  }, {
    firstName: 'Pasquale',
    lastName: 'Reiach',
    email: 'preiach1c@issuu.com'
  }, {
    firstName: 'Binni',
    lastName: 'Dench',
    email: 'bdench1d@hostgator.com'
  }, {
    firstName: 'Fairlie',
    lastName: 'Caberas',
    email: 'fcaberas1e@t-online.de'
  }, {
    firstName: 'Madella',
    lastName: 'Curman',
    email: 'mcurman1f@yelp.com'
  }, {
    firstName: 'Nadine',
    lastName: 'Arnaldy',
    email: 'narnaldy1g@github.com'
  }, {
    firstName: 'Karlis',
    lastName: 'Woffinden',
    email: 'kwoffinden1h@pcworld.com'
  }, {
    firstName: 'Donielle',
    lastName: 'Stockau',
    email: 'dstockau1i@icq.com'
  }, {
    firstName: 'Marketa',
    lastName: 'Moggach',
    email: 'mmoggach1j@soundcloud.com'
  }, {
    firstName: 'Cody',
    lastName: 'Leaman',
    email: 'cleaman1k@boston.com'
  }, {
    firstName: 'Devlin',
    lastName: 'Jacomb',
    email: 'djacomb1l@artisteer.com'
  }, {
    firstName: 'Cornela',
    lastName: 'Fitzhenry',
    email: 'cfitzhenry1m@accuweather.com'
  }, {
    firstName: 'Dilan',
    lastName: 'Greenset',
    email: 'dgreenset1n@businessinsider.com'
  }, {
    firstName: 'Opalina',
    lastName: 'Starbucke',
    email: 'ostarbucke1o@plala.or.jp'
  }, {
    firstName: 'Tiffany',
    lastName: 'Peal',
    email: 'tpeal1p@redcross.org'
  }, {
    firstName: 'Kevin',
    lastName: 'Quye',
    email: 'kquye1q@geocities.jp'
  }, {
    firstName: 'Jeanine',
    lastName: 'Lune',
    email: 'jlune1r@census.gov'
  }, {
    firstName: 'Dicky',
    lastName: 'Laffoley-Lane',
    email: 'dlaffoleylane1s@meetup.com'
  }, {
    firstName: 'Harris',
    lastName: 'Orleton',
    email: 'horleton1t@craigslist.org'
  }, {
    firstName: 'Alexio',
    lastName: 'Petican',
    email: 'apetican1u@ehow.com'
  }, {
    firstName: 'Cointon',
    lastName: 'Blundin',
    email: 'cblundin1v@senate.gov'
  }, {
    firstName: 'Carlie',
    lastName: 'Gilfether',
    email: 'cgilfether1w@infoseek.co.jp'
  }, {
    firstName: 'Wye',
    lastName: 'Zamora',
    email: 'wzamora1x@1688.com'
  }, {
    firstName: 'Hadleigh',
    lastName: 'Warboy',
    email: 'hwarboy1y@mit.edu'
  }, {
    firstName: 'Lesly',
    lastName: 'Filippucci',
    email: 'lfilippucci1z@cisco.com'
  }, {
    firstName: 'Elwira',
    lastName: 'Willacot',
    email: 'ewillacot20@wired.com'
  }, {
    firstName: 'Kendra',
    lastName: 'Spitaro',
    email: 'kspitaro21@miitbeian.gov.cn'
  }, {
    firstName: 'Niles',
    lastName: 'Aphale',
    email: 'naphale22@eepurl.com'
  }, {
    firstName: 'Silvain',
    lastName: 'Loughney',
    email: 'sloughney23@cloudflare.com'
  }, {
    firstName: 'Carling',
    lastName: 'Scranedge',
    email: 'cscranedge24@spiegel.de'
  }, {
    firstName: 'Minnaminnie',
    lastName: 'Keigher',
    email: 'mkeigher25@is.gd'
  }, {
    firstName: 'Ardine',
    lastName: 'Bartram',
    email: 'abartram26@storify.com'
  }, {
    firstName: 'Drusi',
    lastName: 'Beenham',
    email: 'dbeenham27@home.pl'
  }, {
    firstName: 'Mar',
    lastName: 'MacGrath',
    email: 'mmacgrath28@dmoz.org'
  }, {
    firstName: 'Isidore',
    lastName: 'Guthrum',
    email: 'iguthrum29@seattletimes.com'
  }, {
    firstName: 'Sybila',
    lastName: 'Fishly',
    email: 'sfishly2a@vistaprint.com'
  }, {
    firstName: 'Laura',
    lastName: 'Morsey',
    email: 'lmorsey2b@goodreads.com'
  }, {
    firstName: 'Mireielle',
    lastName: 'Aguirrezabal',
    email: 'maguirrezabal2c@arstechnica.com'
  }, {
    firstName: 'Cy',
    lastName: 'Rodenborch',
    email: 'crodenborch2d@jimdo.com'
  }, {
    firstName: 'Kira',
    lastName: 'Peetermann',
    email: 'kpeetermann2e@constantcontact.com'
  }, {
    firstName: 'Inesita',
    lastName: 'Hassen',
    email: 'ihassen2f@surveymonkey.com'
  }, {
    firstName: 'Blondelle',
    lastName: 'De La Salle',
    email: 'bdelasalle2g@si.edu'
  }, {
    firstName: 'Dionysus',
    lastName: 'Harker',
    email: 'dharker2h@buzzfeed.com'
  }, {
    firstName: 'Sibilla',
    lastName: 'Shreeve',
    email: 'sshreeve2i@google.com'
  }, {
    firstName: 'Abe',
    lastName: 'Kerin',
    email: 'akerin2j@list-manage.com'
  }, {
    firstName: 'Reggie',
    lastName: 'Cutten',
    email: 'rcutten2k@technorati.com'
  }, {
    firstName: 'Jacquette',
    lastName: 'Gerault',
    email: 'jgerault2l@blogtalkradio.com'
  }, {
    firstName: 'Gabie',
    lastName: 'Blazic',
    email: 'gblazic2m@alexa.com'
  }, {
    firstName: 'Cesare',
    lastName: 'Wybrew',
    email: 'cwybrew2n@cdbaby.com'
  }, {
    firstName: 'Edita',
    lastName: 'Sobczak',
    email: 'esobczak2o@google.ru'
  }, {
    firstName: 'Terence',
    lastName: 'Pirrone',
    email: 'tpirrone2p@w3.org'
  }, {
    firstName: 'Field',
    lastName: 'Lapish',
    email: 'flapish2q@ftc.gov'
  }, {
    firstName: 'Perri',
    lastName: 'Meineck',
    email: 'pmeineck2r@live.com'
  }
];
